### ISSUE TITLE
Si1132 IR value returns as negative number in bright sunlight

### ISSUE THREAD

**Issue by fraab** [michaelkamprath/ambasat1-flight-software#4]
Minor bug in payload_decoders.js:

ir and visible returned as SignedInts, thus resulting as negative values in bright sunlight.
They should be converted as unsigned ints.

I fixed it by adding a convertTwoBytesToUnsignedInt function:

function convertTwoBytesToUnsignedInt( highByte, lowByte ) {
  var x = (((highByte & 0xFF) << 8) | (lowByte & 0xFF));
  return x;
}

**Comment by michaelkamprath** [comment]
@fraab Thanks. Would you like to open a pull request?

**Comment by fraab** [comment]
Not at this time since it's such a minor change that you can make. Thanks.
