### ISSUE TITLE
A copy/paste bug in Si1132Sensor::setIsInfraRedHighSignalRange(bool setting)

### ISSUE THREAD

**Issue by aromring** [michaelkamprath/ambasat1-flight-software#7]
Hi Michael,
The mentioned bug in Si1132Sensor::setIsInfraRedHighSignalRange(bool setting) is:

_highSignalVisible = setting;

while the function is supposed to set 

_highSignalInfraRed = setting;

**Comment by michaelkamprath** [comment]
Good find. Would you like to issue a pull request?

**Comment by aromring** [comment]
Sorry, I can't because I haven't forked this repository.
